# Main site navigation
[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Posts"
  url = "post/"
  weight = -110

[[main]]
  name = "Projects"
  url = "project/"
  weight = -100

[[main]]
  name = "Armies"
  url = "army/"
  weight = -90

[[main]]
  name = "Rules"
  url = "ruleset/"
  weight = -80

[[main]]
  name = "Suppliers"
  url = "supplier/"
  weight = -70

[[main]]
  name = "About"
  url = "about-us/"
  weight = -60

# social menu links
[[social]]
  name = "twitter"
  type = "social"
  weight = 1
  url = "https://twitter.com/MrJackHughes"
[[social]]
  name = "facebook"
  weight = 2
  url = "https://www.facebook.com/jack.hughes.5832"
[[social]]
  name = "rss"
  weight = 3
  url = "index.xml"
